<a href="https://colab.research.google.com/github/UtsavChauhan80/DSV-/blob/main/Pandas_DataFrames_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Question 1

Create a DataFrame named student_df from a dictionary containing the columns Name, Age, and City for four students.

In [ ]:
import pandas as pd
import numpy as np

student_df = pd.DataFrame({
    "Name": ["Aman", "Priya", "Rahul", "Neha"],
    "Age": [19, 20, 18, 19],
    "City": ["Mathura", "Delhi", "Agra", "Jaipur"]
})
student_df

    Name  Age     City
0   Aman   19  Mathura
1  Priya   20    Delhi
2  Rahul   18     Agra
3   Neha   19   Jaipur

## Question 2

Display the complete student_df DataFrame.

In [ ]:
student_df

    Name  Age     City
0   Aman   19  Mathura
1  Priya   20    Delhi
2  Rahul   18     Agra
3   Neha   19   Jaipur

## Question 3

Write code to display the column names of student_df.

In [ ]:
print(student_df.columns)

Index(['Name', 'Age', 'City'], dtype='object')

## Question 4

Retrieve the Name column from student_df.

In [ ]:
print(student_df["Name"])

0     Aman
1    Priya
2    Rahul
3     Neha
Name: Name, dtype: object

## Question 5

Retrieve the City column from student_df using square-bracket notation.

In [ ]:
print(student_df["City"])

0    Mathura
1      Delhi
2       Agra
3     Jaipur
Name: City, dtype: object

## Question 6

Create a new DataFrame from student_df containing only the columns Name and City.

In [ ]:
name_city_df = student_df[["Name", "City"]]
name_city_df

    Name     City
0   Aman  Mathura
1  Priya    Delhi
2  Rahul     Agra
3   Neha   Jaipur

## Question 7

Create a DataFrame named book_df from a dictionary of equal-length lists containing Book, Author, and Price.

In [ ]:
book_df = pd.DataFrame({
    "Book": ["Python Basics", "Data Science", "Java Guide"],
    "Author": ["A. Sharma", "R. Verma", "S. Kumar"],
    "Price": [350, 500, 420]
})
book_df

            Book     Author  Price
0  Python Basics  A. Sharma    350
1   Data Science   R. Verma    500
2     Java Guide   S. Kumar    420

## Question 8

Add a new column named Publisher to book_df and assign the same publisher name to every row.

In [ ]:
book_df["Publisher"] = "ABC Publications"
book_df

            Book     Author  Price         Publisher
0  Python Basics  A. Sharma    350  ABC Publications
1   Data Science   R. Verma    500  ABC Publications
2     Java Guide   S. Kumar    420  ABC Publications

## Question 9

Create a five-row DataFrame and assign the values generated by np.arange(5) to a new column named SerialNo.

In [ ]:
serial_df = pd.DataFrame({"Item": ["A", "B", "C", "D", "E"]})
serial_df["SerialNo"] = np.arange(5)
serial_df

  Item  SerialNo
0    A         0
1    B         1
2    C         2
3    D         3
4    E         4

## Question 10

Delete the SerialNo column from the DataFrame created in Question 9.

In [ ]:
serial_df = serial_df.drop(columns=["SerialNo"])
serial_df

  Item
0    A
1    B
2    C
3    D
4    E

## Question 11

Create a DataFrame named movie_df containing the columns Movie, Year, and Rating.

In [ ]:
movie_df = pd.DataFrame({
    "Movie": ["3 Idiots", "Dangal", "PK"],
    "Year": [2009, 2016, 2014],
    "Rating": [8.4, 8.3, 8.1]
})
movie_df

      Movie  Year  Rating
0  3 Idiots  2009     8.4
1    Dangal  2016     8.3
2        PK  2014     8.1

## Question 12

From movie_df, create another DataFrame containing the columns Movie, Rating, and a new requested column named Director that is not present in the original DataFrame.

In [ ]:
movie_details_df = movie_df.reindex(columns=["Movie", "Rating", "Director"])
movie_details_df

      Movie  Rating  Director
0  3 Idiots     8.4       NaN
1    Dangal     8.3       NaN
2        PK     8.1       NaN

## Question 13

Create a Series containing two city names at indexes 0 and 3.

In [ ]:
city_series = pd.Series(["Delhi", "Mumbai"], index=[0, 3])
city_series

0     Delhi
3    Mumbai
dtype: object

## Question 14

Assign the Series from Question 13 to a new column named Branch in a four-row DataFrame.

In [ ]:
branch_df = pd.DataFrame({"Student": ["A", "B", "C", "D"]})
branch_df["Branch"] = city_series
branch_df

  Student  Branch
0       A   Delhi
1       B     NaN
2       C     NaN
3       D  Mumbai

## Question 15

Copy a small table from a spreadsheet or webpage and write code to read it into a DataFrame named copied_df using the clipboard-reading method covered in class.

In [ ]:

import pandas as pd

copied_df = pd.read_csv('/content/Table.csv')
copied_df.head()

FileNotFoundError: [Errno 2] No such file or directory: '/content/Table.csv'

## Question 16

Create a five-row DataFrame named employee_df with columns Employee, Department, and Experience. Display only Employee and Experience in a new DataFrame.

In [ ]:
employee_df = pd.DataFrame({
    "Employee": ["Asha", "Ravi", "Karan", "Meena", "Ishaan"],
    "Department": ["IT", "HR", "Sales", "IT", "Finance"],
    "Experience": [2, 5, 3, 7, 1]
})
employee_summary_df = employee_df[["Employee", "Experience"]]
employee_summary_df

  Employee  Experience
0     Asha           2
1     Ravi           5
2    Karan           3
3    Meena           7
4   Ishaan           1

## Question 17

Using employee_df, retrieve the Department column using one-column access and then display all column names.

In [ ]:
print(employee_df["Department"])
print("Column names:", employee_df.columns.tolist())

0         IT
1         HR
2      Sales
3         IT
4    Finance
Name: Department, dtype: object
Column names: ['Employee', 'Department', 'Experience']

## Question 18

Add a new column named Office to employee_df and assign 'Head Office' to every row. Then display the updated DataFrame.

In [ ]:
employee_df["Office"] = "Head Office"
employee_df

  Employee Department  Experience       Office
0     Asha         IT           2  Head Office
1     Ravi         HR           5  Head Office
2    Karan      Sales           3  Head Office
3    Meena         IT           7  Head Office
4   Ishaan    Finance           1  Head Office

## Question 19

Replace the values in the Office column with numbers generated using np.arange(5).

In [ ]:
employee_df["Office"] = np.arange(5)
employee_df

  Employee Department  Experience  Office
0     Asha         IT           2       0
1     Ravi         HR           5       1
2    Karan      Sales           3       2
3    Meena         IT           7       3
4   Ishaan    Finance           1       4

## Question 20

Create a Series named office_names containing 'Delhi', 'Mumbai', and 'Pune' at indexes 0, 2, and 4. Assign it to the Office column of employee_df and display the result.

In [ ]:
office_names = pd.Series(["Delhi", "Mumbai", "Pune"], index=[0, 2, 4])
employee_df["Office"] = office_names
employee_df

  Employee Department  Experience  Office
0     Asha         IT           2   Delhi
1     Ravi         HR           5     NaN
2    Karan      Sales           3  Mumbai
3    Meena         IT           7     NaN
4   Ishaan    Finance           1    Pune

## Question 21

Delete the Office column from employee_df and display the remaining columns.

In [ ]:
employee_df = employee_df.drop(columns=["Office"])
employee_df

  Employee Department  Experience
0     Asha         IT           2
1     Ravi         HR           5
2    Karan      Sales           3
3    Meena         IT           7
4   Ishaan    Finance           1

## Question 22

Create a DataFrame named product_df from a dictionary containing Product, Category, and Price. Then construct another DataFrame with the columns ordered as Price, Product, Category.

In [ ]:
product_df = pd.DataFrame({
    "Product": ["Laptop", "Mouse", "Keyboard"],
    "Category": ["Electronics", "Accessory", "Accessory"],
    "Price": [55000, 700, 1200]
})
ordered_product_df = product_df[["Price", "Product", "Category"]]
ordered_product_df

   Price   Product     Category
0  55000    Laptop  Electronics
1    700     Mouse    Accessory
2   1200  Keyboard    Accessory

## Question 23

Construct a DataFrame from existing data while requesting four columns, where one of the requested columns does not exist in the source data. Display the resulting DataFrame and inspect what appears in the missing column.

In [ ]:
source_df = pd.DataFrame({
    "Name": ["Aman", "Priya"],
    "Age": [19, 20],
    "City": ["Mathura", "Delhi"]
})
requested_df = source_df.reindex(columns=["Name", "Age", "City", "Course"])
requested_df

    Name  Age     City  Course
0   Aman   19  Mathura     NaN
1  Priya   20    Delhi     NaN

## Question 24

Create a DataFrame with a column name containing a space, such as Total Marks. Retrieve that column using the appropriate column-selection syntax demonstrated in the notebook.

In [ ]:
marks_df = pd.DataFrame({
    "Name": ["Aman", "Priya", "Rahul"],
    "Total Marks": [78, 91, 84]
})
print(marks_df["Total Marks"])

0    78
1    91
2    84
Name: Total Marks, dtype: int64

## Question 25

Read a copied table into a DataFrame using pd.read_clipboard(). Display its column names and then create a second DataFrame containing any three selected columns.

In [ ]:

copied_df = pd.read_clipboard()
print(copied_df.columns.tolist())

selected_df = copied_df.iloc[:, :3]
selected_df

PyperclipException:
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit
    https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error

## Question 26

Create a five-row DataFrame named course_df with columns Student, Course, and Score. Then, in sequence: display its column names, retrieve Student, create a DataFrame containing Student and Score, and add a new column named Batch with the same value for all rows.

In [ ]:
course_df = pd.DataFrame({
    "Student": ["Aman", "Priya", "Rahul", "Neha", "Isha"],
    "Course": ["Python", "Java", "Python", "SQL", "Java"],
    "Score": [80, 91, 76, 88, 85]
})
print("Columns:", course_df.columns.tolist())
print(course_df["Student"])
student_score_df = course_df[["Student", "Score"]]
course_df["Batch"] = "B.Tech 1"
print(student_score_df)
course_df

Columns: ['Student', 'Course', 'Score']
0     Aman
1    Priya
2    Rahul
3     Neha
4     Isha
Name: Student, dtype: object
  Student  Score
0    Aman     80
1   Priya     91
2   Rahul     76
3    Neha     88
4    Isha     85

  Student  Course  Score     Batch
0    Aman  Python     80  B.Tech 1
1   Priya    Java     91  B.Tech 1
2   Rahul  Python     76  B.Tech 1
3    Neha     SQL     88  B.Tech 1
4    Isha    Java     85  B.Tech 1

## Question 27

Create a five-row DataFrame named travel_df. Add a column named Code using np.arange(5). Next, replace that column with a Series containing values only at indexes 1 and 4. Display the DataFrame after each assignment.

In [ ]:
travel_df = pd.DataFrame({
    "Destination": ["Agra", "Delhi", "Jaipur", "Lucknow", "Noida"]
})
travel_df["Code"] = np.arange(5)
print("After np.arange(5):")
display(travel_df)

travel_codes = pd.Series(["TR-101", "TR-104"], index=[1, 4])
travel_df["Code"] = travel_codes
print("After assigning partial Series:")
display(travel_df)

After np.arange(5):

  Destination  Code
0        Agra     0
1       Delhi     1
2      Jaipur     2
3     Lucknow     3
4       Noida     4

After assigning partial Series:

  Destination    Code
0        Agra     NaN
1       Delhi  TR-101
2      Jaipur     NaN
3     Lucknow     NaN
4       Noida  TR-104

## Question 28

Create a DataFrame named school_df from a dictionary containing Student, Class, and Section. Construct a second DataFrame requesting the columns Student, Class, Section, and House, even though House is not present in the original data. Then assign one common value to the complete House column.

In [ ]:
school_df = pd.DataFrame({
    "Student": ["Aman", "Priya", "Rahul", "Neha"],
    "Class": [11, 12, 11, 12],
    "Section": ["A", "B", "A", "C"]
})
school_with_house_df = school_df.reindex(columns=["Student", "Class", "Section", "House"])
school_with_house_df["House"] = "Blue"
school_with_house_df

  Student  Class Section House
0    Aman     11       A  Blue
1   Priya     12       B  Blue
2   Rahul     11       A  Blue
3    Neha     12       C  Blue

## Question 29

Create a DataFrame named inventory_df from equal-length lists. Add a new column using a partially indexed Series so that values appear only for selected row indexes. Display the result, then delete the added column and display the DataFrame again.

In [ ]:
inventory_df = pd.DataFrame({
    "Item": ["Pen", "Notebook", "Pencil", "Eraser"],
    "Quantity": [50, 30, 40, 25]
})
stock_series = pd.Series(["Shelf A", "Shelf C"], index=[0, 2])
inventory_df["Shelf"] = stock_series
print("After adding partial Series:")
display(inventory_df)

inventory_df = inventory_df.drop(columns=["Shelf"])
print("After deleting Shelf:")
inventory_df

After adding partial Series:

       Item  Quantity    Shelf
0       Pen        50  Shelf A
1  Notebook        30      NaN
2    Pencil        40  Shelf C
3    Eraser        25      NaN

After deleting Shelf:

       Item  Quantity
0       Pen        50
1  Notebook        30
2    Pencil        40
3    Eraser        25

## Question 30

Copy a table with at least four columns from any webpage or spreadsheet and read it into lab_df. Write one sequence of Pandas statements to: display the DataFrame, display its column names, retrieve one single-word column, retrieve one column whose name contains a space, construct a smaller DataFrame from selected columns, add a new whole column, and finally delete that column.

In [ ]:

lab_df = pd.read_clipboard()
display(lab_df)
print("Columns:", lab_df.columns.tolist())

print("Single-word column:", lab_df.iloc[:, 0])
print("Another column (may contain a space in its name):", lab_df.iloc[:, 1])

small_df = lab_df.iloc[:, :3].copy()
display(small_df)

lab_df["LabStatus"] = "Completed"
display(lab_df)

lab_df = lab_df.drop(columns=["LabStatus"])
display(lab_df)

PyperclipException:
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit
    https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error